# Copy this to config.yml and fill in your API keys.
# Alternatively, set these as environment variables.
malwarebazaar_api_key: "YOUR_KEY_HERE"
threatfox_api_key: "YOUR_KEY_HERE"
yaraify_api_key: "YOUR_KEY_HERE"
